---
title: "Report Part 1"
author: "Trevor Harris"
date: "2/21/2018"
output: pdf_document
---

# Introduction
For the first phase of the Data Assimilation project our goal was to test for, and then quantify, differences between the prior and the posterior ensembles.

So far we have tried to answer the following 3 questions:

1. Is the prior significantly different from the ensemble?
2. If so, where is it different?
3. And if so, by how much is it different

MORE WORDS?

# Data
We used ensembles and the prior from the latest reconstructions in February to perform our analysis. So far we have only considered a small subset of the time points for testing and illustration 

MORE WORDS?

# Methods

## Extremal Depth
To test whether the prior resides within the ensemble we borrow a functional data depth technique called Extremal Depth. Essentially, Extremal Depth measures how "deeply" a function (the prior) sits within a set of other functions (the ensemble). Furthermore, it allows for the construction of central regions which can be used for hypothesis testing. In our case we test if the prior and the ensemble come from the same generating process, if they do not then we say that the prior is significantly different from the ensemble.


## Basis function smoothing


## Differencing

talk about how we take the difference between the prior and the central regions to get "difference coef". Then used the basis functions to map these to a field. 

# Results

## Basis function selection (this may need to go above in the methods section)

Straight from the Bo report

## Differences

straight from the Bo report and add more

# Conclusion

Summarize the above differences section. bring up any unresolved questions.
